### ISSUE TITLE
UI/UX Design

### ISSUE THREAD

**Issue by DevindaWanasinghe** [DevindaWanasinghe/master-art-design-web-platform#7]
- Create wireframes and mockups for user flows (Figma or Sketch).

- Design templates for listing, browsing, and customization interfaces.

- Ensure mobile responsiveness and accessibility.

- Complete Below Figma Designs
- [x]  Account page
- [x] About page
- [x] payment page
- [x] template edit page
- [x] And the rest of the Home page

**Comment by Chalitha-Aluwihare** [comment]
Completed the complete UI/UX design

**Comment by Chalitha-Aluwihare** [comment]
Done

**Comment by DevindaWanasinghe** [comment]
done
